### PR TITLE
Add translation for HTML Head Items

### PR DESCRIPTION
**Pull request by derJuba007**

### CODE REVIEW

**Comment by Kakifrucht** [comment]
Thanks :)
I will be pushing a new release soon!

**Comment by derJuba007** [comment]
No Problem. I will translate a few more in the next few days. :)

**Comment by Kakifrucht** [comment]
Great. keep in mind that the current release doesn't contain all translations that are already done, just make sure to not do duplicated work ;)
I have also mostly done fof/upload already but not pushed yet.

**Comment by derJuba007** [comment]
Allright I will start after the next Release.

**Pull request merged**
